
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 03 12:33:06 EST 2013
//----------------------------------------------------

package compiler488.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 39;
  public static final int WHEN = 20;
  public static final int POOL = 13;
  public static final int PUT = 15;
  public static final int L_PAREN = 26;
  public static final int INTEGER = 3;
  public static final int R_SQUARE = 29;
  public static final int GREATER = 31;
  public static final int R_PAREN = 27;
  public static final int FORWARD = 9;
  public static final int MINUS = 37;
  public static final int LESS = 32;
  public static final int NOT = 23;
  public static final int AND = 21;
  public static final int INTCONST = 41;
  public static final int OR = 22;
  public static final int COMMA = 33;
  public static final int GET = 11;
  public static final int FI = 8;
  public static final int BEGIN = 4;
  public static final int PLUS = 36;
  public static final int LOOP = 12;
  public static final int EXIT = 7;
  public static final int IF = 10;
  public static final int DOT = 34;
  public static final int EOF = 0;
  public static final int BOOLEAN = 2;
  public static final int RETURN = 17;
  public static final int EQUAL = 30;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int IDENT = 40;
  public static final int TIMES = 38;
  public static final int COLON = 35;
  public static final int ELSE = 5;
  public static final int SKIP = 18;
  public static final int L_SQUARE = 28;
  public static final int THEN = 19;
  public static final int TEXTCONST = 42;
  public static final int END = 6;
  public static final int FALSE = 25;
  public static final int PROCEDURE = 14;
  public static final int RESULT = 16;
}

